from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent
RAW_CSV_DIR  = PROJECT_ROOT / "raw_csv"
PARQUET_DIR  = PROJECT_ROOT / "parquet"
SIGNALS_DIR  = PROJECT_ROOT / "signals"
RESULTS_DIR  = PROJECT_ROOT / "results"
SYMBOLS_FILE = PROJECT_ROOT / "symbols.txt"
MERGED_CSV_DIR = PROJECT_ROOT / "data_merged"

BYBIT_ACCOUNT_TYPE    = "UNIFIED"

START_DATE = "2022-01-01"
END_DATE = "2026-01-01"

EMA_FILTER_ENABLED = False
EMA_TIMEFRAME   = "4h"
EMA_FAST_PERIOD = 20
EMA_SLOW_PERIOD = 200

RSI_PERIOD      = 14
RSI_TIMEFRAME   = "1h"
ADX_PERIOD      = 14
ADX_TIMEFRAME   = "1h"

RSI_ENTRY_MIN   = 30
RSI_ENTRY_MAX   = 95
RSI_FILTER_ENABLED = True
RSI_EPS           = 0.5

ADX_FILTER_ENABLED = False
ADX_MIN           = 10
ADX_MAX           = 25

PRICE_BOOM_PERIOD_H = 24
PRICE_BOOM_PCT      = 0.15
PRICE_SLOWDOWN_PERIOD_H = 4
PRICE_SLOWDOWN_PCT      = 0.01


RISK_MODE          = "FIXED"
FIXED_RISK_USDT    = 10.0
FIXED_RISK_CASH    = 10.0

RISK_PCT           = 0.05
SLIPPAGE_BUFFER_PCT = 0.0005
NOTIONAL_CAP_PCT_OF_EQUITY = 1.0


REGIME_SIZE_WHEN_DOWN = 0.2
DYN_MACD_HIST_THRESH = 0.0
REGIME_DOWNSIZE_MULT = 1.0
BTC_VOL_HI = 0.753777980804443


SL_ATR_MULT             = 2.0
FINAL_TP_ENABLED        = True
FINAL_TP_ATR_MULT       = 8.0
PARTIAL_TP_ENABLED      = False
PARTIAL_TP_PCT          = 8.0
PARTIAL_TP_ATR_MULT     = 1.0
TRAIL_ENABLED           = False
TRAIL_START_ATR_MULT    = 1.0
TRAIL_DISTANCE_ATR_MULT = 1.0
TRAIL_MIN_MOVE_PCT      = 0.001


TIME_EXIT_HOURS_ENABLED = True
TIME_EXIT_HOURS         = 4
TIME_EXIT_ENABLED       = True
TIME_EXIT_DAYS          = 10


MIN_COIN_AGE_DAYS = 14
MAX_COIN_AGE_DAYS = 9999


STRUCTURAL_TREND_FILTER_ENABLED = False
STRUCTURAL_TREND_DAYS    = 30
STRUCTURAL_TREND_RET_PCT = 0.01


GAP_FILTER_ENABLED = False
GAP_VWAP_HOURS  = 2
GAP_MAX_DEV_PCT = 1.00
GAP_MIN_BARS    = 3


VWAP_STACK_SIZING_ENABLED = True


VWAP_STACK_LOOKBACK_BARS = 12
VWAP_STACK_BAND_PCT = 0.004
VWAP_STACK_EXPANSION_ABS_MIN = 0.006
VWAP_STACK_EXPANSION_GOOD = 0.015
VWAP_STACK_FRAC_MIN = 0.50
VWAP_STACK_FRAC_GOOD = 0.70


VWAP_STACK_MIN_MULTIPLIER = 0.80
VWAP_STACK_MAX_MULTIPLIER = 1.00
VWAP_STACK_FRAC_WEIGHT = 0.6
VWAP_STACK_EXP_WEIGHT = 0.4


VOL_FILTER_ENABLED  = False
MIN_VOL_USD         = 10000
MAX_VOL_USD         = 5000000000


VOLATILITY_FILTER_ENABLED = False
MIN_ATR_PCT               = 0.005


MAX_OPEN            = 10
MAX_LOSS_STREAK     = 20
KILL_EQUITY_LEVEL   = 50.0
MIN_EQUITY_USDT     = 50.0
MAX_LEVERAGE        = 10
MIN_NOTIONAL        = 0.0000001
MIN_STOP_DIST_USD   = 0.0002
MIN_STOP_DIST_PCT   = 0.000008


DD_PAUSE_ENABLED    = False
DD_MAX_PCT          = 90.0
DD_COOLDOWN_PCT     = 90.0
DD_COOLDOWN_DURATION_H = 4


BTC_FAST_FILTER_ENABLED = False
BTC_FAST_TIMEFRAME      = "5m"
BTC_FAST_EMA_PERIOD     = 20
BTC_SLOW_FILTER_ENABLED = False
BTC_SLOW_TIMEFRAME      = "1h"
BTC_SLOW_EMA_PERIOD     = 200

ALT_SYMBOL              = "ETHUSDT"
ALT_FAST_FILTER_ENABLED = False
ALT_FAST_TIMEFRAME      = "5m"
ALT_FAST_EMA_PERIOD     = 20
ALT_SLOW_FILTER_ENABLED = False
ALT_SLOW_TIMEFRAME      = "1h"
ALT_SLOW_EMA_PERIOD     = 200


BV_RULE_ENABLED   = False
BV_BUCKETS        = 5
BV_MIN_VOL_SPIKE  = [1.2, 1.4, 1.6, 1.8, 2.0]
BV_MAX_VOL_SPIKE  = [6.0, 4.5, 3.5, 2.5, 2.0]


OI_FILTER_ENABLED        = False
OI_LOOKBACK_PERIOD_BARS  = 6
OI_MIN_CHANGE_PCT        = -5.0
OI_MAX_CHANGE_PCT        = 10.0


SCAN_INTERVAL_SEC = 60
TIMEFRAME = '5m'
ENTRY_ORDER_TYPE  = "MARKET"


SYMBOL_COOLDOWN_HOURS = 4


REGIME_BENCHMARK_SYMBOL = "ETHUSDT"


REGIME_CACHE_MINUTES = 60


REGIME_MA_PERIOD = 100
REGIME_ATR_PERIOD = 20
REGIME_ATR_MULT = 2.0


ETH_BAROMETER_ENABLED = True
UNFAVORABLE_MODE = "RESIZE"
UNFAVORABLE_RISK_RESIZE_FACTOR = 0.2


FINALIZE_BACKOFF_SEC        = 120

CANCEL_CLEANUP_BACKOFF_SEC  = 180


META_EXPORT_DIR: str = str(RESULTS_DIR / "meta_export")


STRICT_META_BUNDLE: bool = True


META_REQUIRED_EXTRA_FILES: list[str] = []

